import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../../styles/Details.module.css";
import { useEffect, useState } from "react";
import Loading from "../../components/loading";


export default function Home() {
  
  const [monster, setMonster] = useState(null);

  const {
    query: { id },
  } = useRouter();

  useEffect(() => {
    if (id)
      fetch(`/api/details/${id}`)
        .then((x) => x.json())
        .then(setMonster);
  }, [id]);


  if (!monster) {
    return (
      <Loading />
    );
  }

  return (
    <>
      <Head>
        <title>DQMJ3PRO Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Dqm_j3p_icon.webp" />
      </Head>
      <main className={styles.main}>
        <div className={styles.infoDiv}>
          <div className={styles.actionDiv}>
            <Link href={"/"} className={styles.backLink}>
              <button className={styles.actionButton}>Go Back</button>
            </Link>
            <button className={styles.actionButton}>Edit this monster</button>
            <button className={styles.actionButton}>Delete this monster</button>
          </div>
          <table className={styles.infoTable}>
            <tbody>
              <tr>
                <th>Name</th>
                <td>{monster.name}</td>
              </tr>
              <tr>
                <th>Rank</th>
                <td>{monster.rank}</td>
              </tr>
              <tr>
                <th>Size</th>
                <td>{monster.size}</td>
              </tr>
              <tr>
                <th>Family</th>
                <td>{monster.family}</td>
              </tr>
              <tr>
                <th>HP</th>
                <td>{monster.hp}</td>
              </tr>
              <tr>
                <th>MP</th>
                <td>{monster.mp}</td>
              </tr>
              <tr>
                <th>Attack</th>
                <td>{monster.atk}</td>
              </tr>
              <tr>
                <th>Defense</th>
                <td>{monster.def}</td>
              </tr>
              <tr>
                <th>Agility</th>
                <td>{monster.agi}</td>
              </tr>
              <tr>
                <th>Wisdom</th>
                <td>{monster.int}</td>
              </tr>
              <tr>
                <th>Recipe</th>
                <td>{monster.recipe}</td>
              </tr>
              <tr>
                <th>Skill</th>
                <td>{monster.skill}</td>
              </tr>
              <tr>
                <th>Traits</th>
                <td>{monster.traits}</td>
              </tr>
              <tr>
                <th>Obtainment Methods</th>
                <td>{monster.obtainment}</td>
              </tr>
              <tr>
                <th>Fusion Skill</th>
                <td>{monster.merging_skill}</td>
              </tr>
              <tr>
                <th>Fusion Trait</th>
                <td>{monster.merging_trait}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
