import Head from "next/head";
import styles from "@/styles/Calculator.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import Loading from "../../components/loading";

// fazer tipo uma damage calculator usando os monstros dos players, e tendo alguns bixos tipo bosses como opções pré-feitas

/*
Basic/Status Attack Formula: (Attack - (Def/2)) / 2 + random (-result/16 to +result/16)
Klepto Clobber = 10% of total damage + chance to steal item
Mercurial Thrust does 80% of total damage in exchange of +1 priority
Double-edged Slash does 200% basic attack damage but deals 50% of that damage as recoil
Double Up has +1 priority and does 1.5x basic attack damage up to 200 per hit, but it ignores stat changes for the user's attack stat and makes the user recieve double damage
Multifists hits 4 times with 40% of a basic attack damage per hit, and you can only choose the first target

In DQMJ2, all elemental slashes do dual-elemental damage, and check the lower of the resistances to calc damage
  If the target is weak to either element, it takes 50% more damage regardless of it's other resistance

Metal Slash deals normal damage and guarantees a hit on metal enemies

Family-targeting attacks deal 20% more damage to the associated family (e.g. Material Whirl -> Materials) with no penalty if attacking another family.

The damage of Critical Hits is equal to your attack stat while ignoring the enemy's defense
The base rate of Critical Hits happening is 1/128 or 0.78125% 

-----------------

Spells, Healing, Traits and Resistances at version 1.2 of the calculator

Pearly Gates has an additional 1.3x multipler of damage to all Undead monsters on top of the normal resistance calc

  (559 - (441/2)) / 2 = 169,25
  
  BASIC DAMAGE
    --Maximum Damage--
    169,25 + (169,25 / 16) ~= 179,82

    --Minimum Damage--
    169,25 - (169,25 / 16) ~= 158,67



  SIMPLE SLASHES DAMAGE (+10% increase)
    --Maximum Damage--
    186,17 + (186,17 / 16) ~= 197,80
    
    --Minimum Damage--
    186,17 - (186,17 / 16) ~= 174,53



  ADVANCED SLASHES DAMAGE (+20 ~ 30% increase)
    --Maximum Damage--
    186,17 + (186,17 / 16) ~= 197,80
    
    --Minimum Damage--
    186,17 - (186,17 / 16) ~= 174,53
*/

/* Zweikopf
Psaro basic damage rolls: [167, 161, 159, 178, 166, 179, 176, 162, 175, 166, 162, 172, 162, 158, 160, 169, 165, 178, 165, 164, 166, 176, 166, 167, 174, 162]

Psaro simple slash damage rolls: [198, 189, 190, 182, 177, 195]

Psaro advanced slash damage rolls: []
*/

export default function Home() {
  const [monsters, setMonsters] = useState(null);

  useEffect(() => {
    fetch("/api/monsters/")
      .then((x) => x.json())
      .then(setMonsters);
  }, []);

  if (!monsters) {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>DQMJ3PRO Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Dqm_j3p_icon.webp" />
      </Head>
      <main className={styles.main}>
        <div className={styles.cdDiv}>
          <Link href={"/"} className={styles.backLink}>
            <button className={styles.backButton}>Go Back</button>
          </Link>
        </div>
      </main>
    </>
  );
}
