import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DQMJ3PRO Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Dqm_j3p_icon.webp" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.infoTable}>
          <table>
            <thead>
              <tr>
                <th>Info1</th>
                <th>Fino2</th>
                <th>Nifo3</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>grosso</td>
                <td>três</td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
