import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../../styles/Create.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { register, handleSubmit } = useForm();

  const router = useRouter();

  const onSubmit = (data) => {
    fetch("/api/monsters/create", {
        body: JSON.stringify(data), method: 'POST'
    }).then(() => {
        router.push("/")
    }) 
  }

  return (
    <>
      <Head>
        <title>DQMJ3PRO Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Dqm_j3p_icon.webp" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.infoDiv}>
          <Link href={"/"} className={styles.backLink}>
            <button className={styles.backButton}>Go Back</button>
          </Link>
          <form onSubmit={handleSubmit(onSubmit)}>
            <table className={styles.infoTable}>
              <tbody>
                <tr>
                  <th>Name</th>
                  <td>
                    <input className={styles.dataInput} required {...register("name")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Rank</th>
                  <td>
                    <input className={styles.dataInput} required {...register("rank")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Size</th>
                  <td>
                    <input className={styles.dataInput} required {...register("size")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Family</th>
                  <td>
                    <input className={styles.dataInput} required {...register("family")}></input>
                  </td>
                </tr>
                <tr>
                  <th>HP</th>
                  <td>
                    <input className={styles.dataInput} required {...register("hp")}></input>
                  </td>
                </tr>
                <tr>
                  <th>MP</th>
                  <td>
                    <input className={styles.dataInput} required {...register("mp")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Attack</th>
                  <td>
                    <input className={styles.dataInput} required {...register("atk")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Defense</th>
                  <td>
                    <input className={styles.dataInput} required {...register("def")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Agility</th>
                  <td>
                    <input className={styles.dataInput} required {...register("agi")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Wisdom</th>
                  <td>
                    <input className={styles.dataInput} required {...register("int")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Recipe</th>
                  <td>
                    <input className={styles.dataInput} required {...register("recipe")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Skill</th>
                  <td>
                    <input className={styles.dataInput} required {...register("skill")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Traits</th>
                  <td>
                    <input className={styles.dataInput} required {...register("traits")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Obtainment Methods</th>
                  <td>
                    <input className={styles.dataInput} required {...register("obtainment")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Fusion Skill</th>
                  <td>
                    <input className={styles.dataInput} required {...register("merging_skill")}></input>
                  </td>
                </tr>
                <tr>
                  <th>Fusion Trait</th>
                  <td>
                    <input className={styles.dataInput} required {...register("merging_trait")}></input>
                  </td>
                </tr>
              </tbody>
            </table>
            <input type="submit" hidden />
          </form>
        </div>
      </main>
    </>
  );
}
