import Head from "next/head";
import styles from "../../styles/Create.module.scss";
import Link from "next/link";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { useEffect } from "react";

export default function Create() {
  const theme =
    typeof window !== "undefined" ? window.localStorage.getItem("theme") : "";
  const icon =
    typeof window !== "undefined" ? window.localStorage.getItem("icon") : "";
  const { register, handleSubmit } = useForm();

  useEffect(() => {
    if (typeof window === "undefined") return;

    document.body.classList.add(styles[theme]);

    return () => {
      document.body.classList.remove(styles[theme]);
    };
  }, [theme]);

  const router = useRouter();

  const onSubmit = (data) => {
    fetch("/api/monsters/create", {
      body: JSON.stringify(data),
      method: "POST",
    }).then(() => {
      router.push("/");
    });
  };

  return (
    <>
      <Head>
        <title>DQMJ3PRO Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={icon} />
      </Head>
      <div className={styles[theme]}>
        <main className={styles.main}>
          <div className={styles.infoDiv}>
            <Link href={"/"} className={styles.backLink}>
              <button className={styles.backButton}>Go Back</button>
            </Link>
            <form onSubmit={handleSubmit(onSubmit)}>
              <table className={styles.infoTable}>
                <tbody>
                  <tr>
                    <th>Name</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("name")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Rank</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("rank")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Size</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("size")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Family</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("family")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>HP</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("hp")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>MP</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("mp")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Attack</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("atk")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Defense</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("def")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Agility</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("agi")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Wisdom</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("int")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Recipe</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("recipe")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Skill</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("skill")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Traits</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("traits")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Obtainment Methods</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("obtainment")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Fusion Skill</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("merging_skill")}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <th>Fusion Trait</th>
                    <td>
                      <input
                        className={styles.dataInput}
                        required
                        {...register("merging_trait")}
                      ></input>
                    </td>
                  </tr>
                </tbody>
              </table>
              <input type="submit" hidden />
            </form>
          </div>
        </main>
      </div>
    </>
  );
}
